### PR TITLE
Update home.html for footer metakgp banner

### LINKED ISSUE #2: Missing the metakgp banner
There is no footer on the project that shows the usual MetaKGP banner: 'Maintained by MetaKGP with ♥'.

### PR DESCRIPTION
**Pull request by aditimaurya**
Here I'm attaching the screenshots both from web and mobile view.
Screenshot (190)
Screenshot (188)

### CODE REVIEW

**Comment by thealphadollar** [comment]
@aditimaurya Do you think we can add the CSS update in this PR itself? I believe both together solve the issue, right?

**Comment by aditimaurya** [comment]
@thealphadollar I was trying to merge both the branches in one inorder to make a single pull request but after following multiple pages on google I wasn't able to do so and hence I made two pull requests. 
I tried this but I don't know why it wasn't working:
Screenshot (197)
Screenshot (198)

**Comment by thealphadollar** [comment]
Interesting, no issues. We can help you out. However, the below sentence is far from helpful to us in helping you.

> I wasn't able to do so

Please tell us what exact issue did you face while trying to merge, what was the error, and any other information that would help us in understanding the issue you are facing and support you in solving it.

[This guide](https://rogerdudler.github.io/git-guide/) will be helpful to you, just in general, in understanding how to use git and Github. This is very crucial otherwise you'll keep facing issues like this.

**Comment by aditimaurya** [comment]
While following the commands in the Vscode terminal, there was no such error or issue shown by it neither any compilation error, but when I see my GitHub profile, it wasn't updated.  So after that, I try merging them via GitHub desktop in that there was a conflicting issue, but somehow I solved it, but again, when I came to my GitHub profile, it wasn't updated, shows two different branches. So as such, there's no issue or error, but after using these commands, there was no update in my GitHub profile.

**Comment by thealphadollar** [comment]
Did you push the new (updated branch with merges from the two separate branches) branch to your remote?

**Review by grapheo12 — CHANGES_REQUESTED** [review]
Good work! But don't you think the footer has too small height.
There is plenty of blank space around it. You can go ahead and make the font a little bigger (+5pt maybe).
And add sufficient padding. The more you add padding, the more you allow your components to breathe

**Comment by aditimaurya** [comment]
@thealphadollar in github desktop when I clicked on "publish branch" icon a message pop up regarding the commits aren't available in local branch so for that there was an option of fetch new commits, after that, I saw a conflicting issue with my commits and things got complicated, and I chose to put two different PR's and commit directly by github.
I'll refer to the link that you have provided and will assure to get a good command on GitHub. And from the next time I'll keep these things in mind :)

**Comment by thealphadollar** [comment]
> from the next time I'll keep these things in mind :)

That sounds good to me, next time I know you'll do much better with the pace you are learning at.

**Review by thealphadollar — APPROVED** [review]
Voohoo! This looks amazing to me, thanks @aditimaurya for fixing the issue.

**Comment by thealphadollar** [comment]
@aditimaurya I've pushed two small commits, please have a look at them. I'll merge this once @grapheo12 has approved #7

**Pull request merged**
