### PR TITLE
Update main.css for footer metakgp banner

### LINKED ISSUE #2: Missing the metakgp banner
There is no footer on the project that shows the usual MetaKGP banner: 'Maintained by MetaKGP with ♥'.

### PR DESCRIPTION
**Pull request by aditimaurya**
I've added the footer in this project which contains the banner of metakgp along with the links of this github project and metakgp's homepage link. As there is no specific color was mentioned for the background in the issue so I've chosen white by default. If there's any change do let me know.

### CODE REVIEW

**Comment by aditimaurya** [comment]
Screenshot (225)

Screenshot (224)

**Comment by aditimaurya** [comment]
@grapheo12 please have a look in the new changes :)

**Review by thealphadollar — APPROVED** [review]
This looks good to me! Yayy, @aditimaurya 

Once @grapheo12 has given his nod, I'll merge this.

**Comment by grapheo12** [comment]
This looks fantastic. Please merge.

**Pull request merged**
